unjs/unbuild

build.config.ts

Previous code would work if `unbuild` had previously been built (e.g. with `dist/index.js` in place) - this makes it work in CI/dev.

build: allow first build to work

---

package.json
src/builder/untyped.ts
yarn.lock

BREAKING CHANGES: requires node 12+ and support for subpath exports
resolves #13

chore!: upgrade `untyped`

---

src/builder/rollup.ts

`export * from` does not forward default exports.

fix(stub): re-export `default` in dts stub

---

src/cli.ts

Edit: Seems like a regression from https://github.com/unjs/unbuild/commit/12ccc15d42a360995280aec057e44cb1bfba0c87.
----
In practice, many tools rely on `/usr/bin/env` as the more commonly recommended way instead of `/bin/env`.
For example, using `nvm` or `fnm`, `/bin/env` won't work, at least on my system.

fix: shebang support

---

src/builder/rollup.ts

Ensure the directory for each input file is created (recursively) before writing any files.
closes #39

fix(rollup): ensure output subdirectory exists

---

src/validate.ts
test/validate.test.ts

Let's say I have `next` in `peerDependencies`, and the following import in my package: 
```
import something from "next/head"
```
When building the package with `unbuild`, it shows a warning: `Potential implicit dependencies found: next/head`, while I think it should be legal to use import from peerDeps.
Let me know if I should make any changes.
---
Thank you for building `unbuild` 🔥

feat: allow peerDeps as import entry points

---

package.json

Currently, `build.config.ts` does not compat with `"moduleResolution": "Node16"` in tsconfig.
An alternative solution is to support `build.config.mts`
**Before**
**After**

fix(pkg): add types field for exports

---

src/auto.ts
test/auto.test.ts

fix: match least-nested files first when inferring entry

---

src/builder/rollup.ts

Previously when including `package.json` or other local file that is resolved to an absolute path, unbuild would identify this as an external on windows systems, as the absolute path didn't start with `/` but with `C:\`

fix: do not throw error on absolute windows paths

---

src/builder/plugins/esbuild.ts

This PR fixes https://github.com/unjs/unbuild/issues/112 by preventing the execution of code modification on d.ts files.

fix: prevent minification of `.d.ts` files

---

src/builder/rollup.ts

rollop alias option from config file like 
```js
rollup: {
alias: {
entries: [
{
find: '@shared/types',
replacement: path.resolve(projectRootDir, 'src/shared/types'),
},
],
}
}
```
entries above wouldn't get the right alias config since `unbuild` does not handle this scene.
This PR is related to https://github.com/unjs/unbuild/issues/221

fix(rollup): handle array format for `rollup.alias.entries` option

---

src/builder/rollup.ts

In rollup3, you need to configure  [interop](https://rollupjs.org/configuration-options/#output-interop) to `compat` for cjs to work properly
```ts
const esm = require('esm-lib')
console.log(esm)
```
```ts
const esm = require('esm-lib')
function _interopDefaultCompat(e) {
return e && typeof e === 'object' && 'default' in e
? e
: { default: e };
}
console.log(_interopDefaultCompat(esm))
```

fix(rollup): enable `interop: compat` for cjs compatibility

---

README.md

This is [required](https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing) for TypeScript to work under `"module": "node16"`, see https://github.com//microsoft/TypeScript/issues/47792.

docs: add `types` to default `exports`

---

src/build.ts
src/builder/rollup.ts
src/types.ts

When inlining node module dependencies, this can be helpful to analyze bundle impact for all modules.

feat(rollup): show size of bundled npm packages in cli output

---

src/auto.ts
test/auto.test.ts

fix: respect directory separator when matching entries

---

README.md
package.json
src/auto.ts
src/builder/mkdist.ts
src/builder/rollup.ts
src/types.ts
test/auto.test.ts

feat: generate index.d.mts and index.d.cts

---

src/builder/plugins/esbuild.ts
src/types.ts

This PR improves esbuild option handling, separating custom options and removing unused `typescript` key and also remove deprecated `sourceMap` alias

refactor(rollup)!: improve esbuild options handling

---

src/builder/rollup.ts

With this change, it allows to externalize a specific module path like internal modules.
Fixes #269.

fix(rollup): check module id against externals as well

---

src/build.ts
test/fixture/build.config.ts
test/fixture/package.json
test/fixture/src/nested/subpath.ts

Context: #251
This PR adds support for nested subpaths (in a directory) for rollup builds (both automated and custom supported)
See implementation notes in https://github.com/unjs/unbuild/pull/251#issuecomment-1640113666

feat: support nested subpaths

---

src/auto.ts
test/auto.test.ts
test/fixture/bin/cli.mjs
test/fixture/package.json

When a build entry exists outside of build tool, we should avoid making warnings.
Fun: I just spent today maintaining unbuild issues to only fix this one finally for listhen bin issue :D

fix(auto): avoid warning for existing files

---

src/auto.ts

Update an outdated JSDocs comments on `inferEntries` function.

chore: update jsdocs for `ìnferEntries`

---

src/build.ts

https://github.com/nuxt/module-builder/pull/181#issuecomment-1794566118
Not quite sure how to categorise, but this bumps esbuild target from `es2020` to `esnext`. However, we might consider using a year-bound target (https://esbuild.github.io/content-types/#javascript) to fix the feature-set.

feat(rollup)!: default to `esnext` build target

---

package.json
pnpm-lock.yaml
src/build.ts

Let us draw a curtain of charity over how I discovered this issue.
I also considered warning + continue in this case but thought there would be valid use cases, such as wanting `./src/my-file.ts` to output to `./some-file.js`. However, if this is too edge-casey, I think we could add a warning as well.

fix: don't clean root directory if set as `outDir`

---

package.json
pnpm-lock.yaml
src/build.ts
src/builder/rollup.ts
src/builder/untyped.ts
src/types.ts
src/utils.ts

Upgrade unbuild internals and stubs to leverage jiti v2 (beta)
Noticeable changes:
- Native ESM will be used as much as possible
- Interopdefault is not applied by default
- Stubs use relative paths with corresponding .mjs or .cjs entry of jiti

feat: upgrade to jiti v2 beta

---

README.md
eslint.config.mjs
examples/1.zero-config/src/utils.ts
examples/3.untyped/src/index.ts
src/auto.ts
src/build.ts
src/builders/copy/index.ts
src/builders/mkdist/index.ts
src/builders/rollup/build.ts
src/builders/rollup/config.ts
src/builders/rollup/plugins/cjs.ts
src/builders/rollup/plugins/esbuild.ts
src/builders/rollup/plugins/raw.ts
src/builders/rollup/plugins/shebang.ts
src/builders/rollup/stub.ts
src/builders/rollup/utils.ts
src/builders/rollup/watch.ts
src/builders/untyped/index.ts
src/utils.ts
src/validate.ts
test/validate.test.ts

add explicit return types for isolated declaration build support (#411)

refactor: add explicit return types

---

package.json
pnpm-lock.yaml
src/build.ts
src/builders/copy/index.ts

Under the hood, `globby` is powered by `fast-glob` with extra features, but none of them are utilized by the `unbuild`.
Since the `unbuild` doesn't utilize those extra features, I propose replacing `globby` with `fast-glob` to reduce the installation size.
Here is globby's feature description:
- Promise API
- `fast-glob` also has promise-based API
- Multiple patterns
- `globby`'s multiple patterns support is powered by `fast-glob` directly
- Negated patterns: `['foo*', '!foobar']`
- `globby`'s negated patterns support is also powered by `fast-glob` directly
- Expands directories: `foo → foo/**/*`
- `unbuild` doesn't rely on this feature
- Supports `.gitignore` and similar ignore config files
- `unbuild` doesn't rely on this feature since `globby` disabled this feature by default and …

refactor: replace `globby` w/ `fast-glob`

---

package.json
pnpm-lock.yaml
src/build.ts
src/builders/copy/index.ts

[`fast-glob`](https://npmgraph.js.org/?q=fast-glob) - 17 subdependencies
[`tinyglobby`](https://npmgraph.js.org/?q=tinyglobby) - 2 subdependencies
https://github.com/es-tooling/module-replacements/blob/main/docs/modules/glob.md#tinyglobby
See unjs/mkdist#237
Like #418 but switches to an even smaller library

refactor: replace fast-glob with tinyglobby

---

src/build.ts
src/utils.ts
test/utils.test.ts

resolves #351 (and some reported in #201)
This PR automatically infers externals (to avoid warning) from package.json `name`, `exports` and `imports` field (+ `optionalDependencies`)

feat: infer externals from package name, exports and imports

---

package.json
pnpm-lock.yaml
src/builders/rollup/config.ts

`@rollup/plugin-node-resolve` v16 enforces conditions to have at least `production` or `development`. Default is infered from `NODE_ENV` and if (is set and) it is not `=== "production"` (which in many scripts is not) will become `development`. (more info: https://github.com/rollup/plugins/pull/1823)
this PR updates plugin + uses `["production"]` as the condition by default to ensure prod optimized builds (overridable by users still)

feat(rollup): resolve with `production` condition

---

src/utils.ts
test/utils.test.ts

#469 wrongly added all `devDependencies` as externals which is wrong (they are not shipped). this PR adds only `@types/*` dev deps as implicit externals which is usually desired.

fix: only externalize `@types/` from `devDependencies`

---

src/builders/mkdist/index.ts

This uses compiler error data from `mkdist` to respect `failOnWarn` from `unbuild`:
Note: TS is very forgiving and I had to set `noEmitOnError: true` to generate an error for testing. Normally TS errors like the one shown in the screenshot don't cause issues emitting declarations.

feat(mkdist): fail build if `mkdist` errors in creating declarations

---

src/builders/rollup/build.ts
src/builders/rollup/plugins/cjs.ts

fix: correct `.d.cts` default export type

---

src/builders/rollup/config.ts

After #483 fix, all aliases are recursively resolved, therefore checks that were working against originalId, start to fail (https://github.com/nitrojs/nitro/actions/runs/12746727154/job/35523356888)
This PR includes generic improvements for externals by having additional ext rule checks against both originalId and resolvedId.

fix(rollup): improve external detection

---

src/builders/rollup/build.ts

resolves #396
resolves #135
The rollup-plugin-dts conflicts with @rollup/plugin-commonjs:
> The plugin does its own import resolution through the typescript compiler, and usage together with other resolution plugins, such as node-resolve can lead to errors and is not recommended.
> [rollup-plugin-dts - what-to-expect](https://github.com/Swatinem/rollup-plugin-dts?tab=readme-ov-file#what-to-expect)
I'm not sure if it's okay to simply remove @rollup/plugin-commonjs when generating declarations. 🤔 
I've tested some common cases, and it's working fine.

fix: filter commonjs plugin when generating declaration

---

src/builders/rollup/types.ts

resolves https://github.com/unjs/unbuild/issues/539

docs: remove wrong jsdoc for `dts` type
